### ISSUE TITLE
直接托管到vercel，部署失败

### ISSUE THREAD

**Issue by motto1** [LaughingZhu/DevNow#104]
![1733731168016](https://github.com/user-attachments/assets/44351b31-7d21-420a-9ce2-10a7c600f593)
尝试了fork后部署也是同样的问题，是我操作不对吗？:L

**Comment by LaughingZhu** [comment]
![image](https://github.com/user-attachments/assets/6499c633-2dfb-4501-bf20-1a262bfd0d99)
在 vercel 的项目设置中，把 node 版本先改成20，vercel 更新了 node 的版本，我看下怎么升级下

**Comment by LaughingZhu** [comment]
https://vercel.com/changelog/node-js-22-lts-is-now-available 新版本的公告，为啥我 邮箱 刚刚收到 😂

**Comment by motto1** [comment]
> ![image](https://private-user-images.githubusercontent.com/20132891/394275799-6499c633-2dfb-4501-bf20-1a262bfd0d99.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM5ODcyMjYsIm5iZiI6MTczMzk4NjkyNiwicGF0aCI6Ii8yMDEzMjg5MS8zOTQyNzU3OTktNjQ5OWM2MzMtMmRmYi00NTAxLWJmMjAtMWEyNjJiZmQwZDk5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjEyVDA3MDIwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZiNzEyZTliMDVkOWU0ZTk4NGQ5ZDI5MzUyNzBiZjE5Njk4ZmJkODYzZDUxODZlMDAxMTdiMTg3M2RlMzg0YTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.u4VVTZO38RgmtkOGuo0D3lyBiiRjZG19WVtEssFFeTs) 在 vercel 的项目设置中，把 node 版本先改成20，vercel 更新了 node 的版本，我看下怎么升级下

我发完查了一下也发现了要改node版本就行了😂

**Comment by zhx1012** [comment]
![Image](https://github.com/user-attachments/assets/2634087f-9ed1-4f9c-9f50-077001e15642)
![Image](https://github.com/user-attachments/assets/119ad2c5-2009-4936-b152-24243777def4)

node 版本先改成20还是报错，还需要设置什么吗？
