### ISSUE TITLE
个人域名配置问题

### ISSUE THREAD

**Issue by zhx1012** [LaughingZhu/DevNow#111]
![image](https://github.com/user-attachments/assets/ac196005-cf65-4b3f-8de3-a1ea205b3443)
![image](https://github.com/user-attachments/assets/48386758-2288-4f8e-989f-851125c5e033)

Hi，我在Vercel中添加了自己的www域名。DNS 解析服务使用的Cloudflare，外网环境可以访问，但是打开cf代理后国内外都会进不去，Vercel的域名状态也会提示错误。想请教一下怎么解决，使用根域名可以实现普通环境下实现访问吗？我有尝试再加A记录cf会提示错误，不知道是不是因为Nas绑定了ipv6的地址

**Comment by LaughingZhu** [comment]
啊，我也是这么配置的，都代理了，目前一直正常，没有遇到这个问题诶。
**Vercel的域名状态也会提示错误** ： 有提示啥错误吗，或者等一小会，是不是解析还没生效，这块我也不是特别懂，我默认都是全球用户了😂

**Comment by zhx1012** [comment]
![image](https://github.com/user-attachments/assets/b6950d8b-7679-44e9-8451-d978ce362565)
![image](https://github.com/user-attachments/assets/0deba4f5-6a27-422a-bbf4-3d79efd83f19)
cf开代理会提示“Invalid Configuration”

**Comment by zhx1012** [comment]
![image](https://github.com/user-attachments/assets/28f48599-13bd-4814-90b0-19fd085d9d7f)
![image](https://github.com/user-attachments/assets/dfcaa351-f4c1-4335-8396-cc38d8607ba9)

已解决，cf不开代理，Vercel设置部署的地区为香港~

**Comment by LaughingZhu** [comment]
> ![image](https://private-user-images.githubusercontent.com/103342885/398576252-28f48599-13bd-4814-90b0-19fd085d9d7f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUxNzIwMDksIm5iZiI6MTczNTE3MTcwOSwicGF0aCI6Ii8xMDMzNDI4ODUvMzk4NTc2MjUyLTI4ZjQ4NTk5LTEzYmQtNDgxNC05MGIwLTE5ZmQwODVkOWQ3Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyNlQwMDA4MjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MDEyODA5MjFmMDdhNjg0ZjlhMDFhNjlmYWJkZjg2NDZiM2ViNjhhOGQ1NmE0YTQ3ZjE4MjM5YzEyZmY0MWYxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.6uqgfKCw9epWqqzX_2cdEmKBiQ0WiSQPpk_2wR9AHds) ![image](https://private-user-images.githubusercontent.com/103342885/398576271-dfcaa351-f4c1-4335-8396-cc38d8607ba9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUxNzIwMDksIm5iZiI6MTczNTE3MTcwOSwicGF0aCI6Ii8xMDMzNDI4ODUvMzk4NTc2MjcxLWRmY2FhMzUxLWY0YzEtNDMzNS04Mzk2LWNjMzhkODYwN2JhOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyNlQwMDA4MjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZDhmYzhmZTExOTM1OTAzMTc0MGFjN2U2NzNiOWVmNWZjOGFjY2E4OWE2YmU0MTZjODI5ZDE3Yjg5YTQyNDM0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.QG9KRYfWzhb6oCHhcZ0Afro_ne1pDqB-5xTivKGrF4I)
> 
> 已解决，cf不开代理，Vercel设置部署的地区为香港~

棒，可以，我也记录下，以防后边遇到想同的问题。Vercel 我好像选的美国的。
