### ISSUE TITLE
DevNow版本更新问题

### ISSUE THREAD

**Issue by zhx1012** [LaughingZhu/DevNow#112]
后续如果添加新功能或者有新的优化更新，请问如何同步到已部署的博客上呢？

**Comment by LaughingZhu** [comment]
如果是 fork 的话，可以通过 sync 来同步；或者建一个远程分支，然后merge一下。除了自定义的config 和 文章内容，其他的可以默认使用 DevNow 更新的内容。

<img width="959" alt="image" src="https://github.com/user-attachments/assets/d6ff43f1-d507-4c89-99c2-8982774358fa" />

不过还是建议 diff 一下，避免自己业务中有修改导致有冲突。
