### ISSUE TITLE
消息称微软将关闭全国所有线下授权门店，仅保留官网商城 / 京东旗舰店

### ISSUE THREAD

**Issue by heyeverybod1** [LaughingZhu/DevNow#6]
### 消息称微软将关闭全国所有线下授权门店，仅保留官网商城 / 京东旗舰店

有网友反馈微软将于今天（7 月 1 日）起关闭全国所有线下授权门店。

据悉，微软进行相关举动的原因是该公司正在全球范围内对 Surface 设备进行“战略调整”，此外“中国大陆地区的消费者对 Surface 的认可度一直在降低”。

此外，微软中国的线上零售业务将只保留微软中国官方商城官网和微软京东自营官方旗舰店，微软中国的线下授权门店将全部关闭，全国官方售后维修点依然保留。而这据称也是“很多消费者到线下询问 Pro 11 / Laptop 7 发现门店没有样机的原因”。

**Comment by LaughingZhu** [comment]
good job
