### ISSUE TITLE
请问如何能访问这么快的?

### ISSUE THREAD

**Issue by kingwrcy** [LaughingZhu/DevNow#79]
请问作者域名在cf,套了cf,实际部署在vercel吗?我用itdog看全国测速耗时都是1秒以内.

但是cf在国内访问不是减速的吗?

为啥你这个这么快,怎么弄的?

**Comment by LaughingZhu** [comment]
诶，这个我还真没注意，我是腾讯买的域名，然后 DNS 解析服务换成了 cf上，部署是在vercel。其他的没做啥操作呀😂

**Comment by LaughingZhu** [comment]
这个迁移cdn图床的时候切换到 cf 的一些内容 https://www.laughingzhu.cn/posts/cloudflare-r2

**Comment by LaughingZhu** [comment]
今天改东西的时候看，我默认开启了 ISR 。然后导致一个问题就是，每次部署完只有第一次访问会走到 vercel 的服务，其余都都会走到vercel 的缓存服务，这个应该是快的原因。 可以在页面响应头里看到 
<img width="1080" alt="image" src="https://github.com/user-attachments/assets/54615874-1f07-4223-9cb4-02b79396f679">
这个属性只有在第一次访问会 MISS，其余不管换浏览器还是刷新都是 HIT，命中缓存，导致快的。你可以看你自己的部署的服务，我在我的博客项目中已经改掉了，现在明显慢了。

**Comment by kingwrcy** [comment]
怪不得,现在的确慢多了,.原来是开启了缓存.
