### ISSUE TITLE
blog 的左侧目录无法滚动，会导致在目录很多加上屏幕比较小的情况下会隐藏掉一部分目录。

### ISSUE THREAD

**Issue by LaughingZhu** [LaughingZhu/DevNow#82]
blog 的左侧目录无法滚动，会导致在目录很多加上屏幕比较小的情况下会隐藏掉一部分目录。

_Originally posted by @shenweiyan in https://github.com/LaughingZhu/DevNow/issues/75#issuecomment-2328180575_

**Comment by LaughingZhu** [comment]
![image](https://github.com/user-attachments/assets/1330c52e-8188-41fd-a5ae-b09758746458)


这种情况吗，确实在一些场景下会出现这样的问题，可能和我的使用方式有差异，我可能都是在右边的内容区来浏览，很少用左侧的目录，没注意到这种情况。我记录下

**Comment by shenweiyan** [comment]
的确是这样子，有时候对于一些篇幅很长的文章，有些人会喜欢先看目录，再选中特定的章节去阅读。

**Comment by LaughingZhu** [comment]
@shenweiyan fixed  #84
